print("---------------------------------------------------------------------------------------------------")
print("Vamos ler dois números, vamos subtraiar seus valores, some 10 ao resultado mostre o valor")
num_1 = float(input("Digite o primeiro número: "))
num_2 = float(input("Digite o segundo número: "))
result_1 = num_1 - num_2
result_2 = result_1 + 10
print(f"O resultado dos cálculos são {result_2}")